name: mindcoach
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  cross_fade: ^0.5.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  auto_size_text: ^3.0.0
  flutter_markdown: ^0.7.7+1
  wheel_chooser: ^1.1.2
  lottie: ^3.3.2
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  flutter_slidable: ^4.0.3
  flutter_calendar_carousel: ^2.5.4
  table_calendar: ^3.2.0
  percent_indicator: ^4.2.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  generate: true # dil dosyasını üretmesi için
  assets:
   - assets/
   - assets/json/
   - assets/chars/
   - assets/icons/
   - assets/policies/en/
   - assets/policies/tr/
   - assets/policies/de/
   - assets/svg/
   - assets/images/



flutter_native_splash:
  color: "#FFFFFF" # splash bg color
  image: "assets/logo/appicon.png" # resmin yolu
  android: true # Android
  ios: true     # iOS

  android_12:
    color: "#FFFFFF"
    image: "assets/logo/appicon.png"
