name: mindcoach
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.7+57

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  cross_fade: ^0.5.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  auto_size_text: ^3.0.0
  flutter_markdown: ^0.7.7+1
  wheel_chooser: ^1.1.2
  lottie: ^3.3.2
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  flutter_slidable: ^4.0.3
  flutter_calendar_carousel: ^2.5.4
  table_calendar: ^3.2.0
  percent_indicator: ^4.2.5
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.3
  devicelocale: ^0.8.2
  image_picker: ^1.2.1
  record: ^6.1.2
  audio_waveforms: ^1.0.3
  path_provider: ^2.1.2
  audioplayers: ^6.1.0
  just_audio: ^0.9.40
  flutter_pcm_sound: ^3.3.3
  flutter_3d_controller: ^2.3.0
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  http_parser: ^4.0.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  uuid: ^4.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  in_app_notification: ^1.1.2
  onesignal_flutter: ^5.3.5
  rive: ^0.14.0
  webview_flutter: ^4.13.1
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  iconsax_flutter: ^1.0.1
  flutter_confetti: ^0.5.1
  purchases_flutter: ^9.9.7
  purchases_ui_flutter: ^9.9.7
  cached_network_image: ^3.4.1
  #google_mlkit_face_detection: ^0.13.1
  camera: ^0.11.3
  permission_handler: ^11.4.0
  share_plus: ^11.0.0
  posthog_flutter: ^5.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true # dil dosyasını üretmesi için
  assets:
    - assets/
    - assets/json/
    - assets/chars/
    - assets/icons/
    - assets/premiumCard/
    - assets/analyse/
    - assets/policies/en/
    - assets/policies/tr/
    - assets/policies/de/
    - assets/svg/
    - assets/images/
    - assets/sounds/
    - assets/musics/

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  alpha_background: true
  image_path: assets/icons/app_icon.jpeg
